trigger: none

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Start Building...'
  timeoutInMinutes: 9999

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/SachithDilshan404/Photos-rep/main/Downloads.bat" -OutFile "Downloads.bat"
    displayName: 'Downloading Essentials'

  - script: |
      cmd /c Downloads.bat
    displayName: 'Installing Essentials'

  - script: |
      cmd /c show.bat
    displayName: 'Log In To AnyDesk'

  - script: |
      python time.py
    displayName: 'Time Counter'