trigger:
- main
stages:
- stage: setup
  jobs:
  - job: windows_setup
    timeoutInMinutes: 9999
    cancelTimeoutInMinutes: 5
    pool:
      vmImage: 'windows-2022'
    steps:
    - powershell: |
        # Downloading & Installing Essentials
        Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/SachithDilshan404/Photos-rep/main/Downloads.bat'-OutFile 'Downloads.bat'
        cmd /c Downloads.bat
      displayName: 'Downloading & Installing Essentials'
    - powershell: |
        cmd /c show.bat
      displayName: 'Log In To RustDesk'
    - powershell: |
        python time.py
      displayName: 'Time Counter'

  
